### ISSUE TITLE
FastBoot

### ISSUE THREAD

**Issue by mhluska** [outdoorsy/ember-experiments#10]
I'm considering using this in a project. Has this been tested with FastBoot?

**Comment by kiwiupover** [comment]
We are using it with Fastboot.  The fastboot response is cached then on the client the experiment is set and metrics are sent. Let me know if you have more questions. 

Also checkout outdoorsy.com you will see experiments being set there.

**Comment by mhluska** [comment]
Awesome. Thanks for the quick response.
